### ISSUE TITLE
Missing event_time in AndroidNotification

### ISSUE THREAD

**Issue by star1ite** [firebase/firebase-admin-dotnet#267] opened 2020-10-26 09:05 UTC
I want to specify actual event time for notification, but i cannot do it in this library...

REST specification for AndroidNotification:
{
  "title": string,
  "body": string,
   ...
  **"event_time": string,**
   ...
}

event_time | string (Timestamp format)Set the time that the event in the notification occurred. Notifications in the panel are sorted by this time. A point in time is represented using protobuf.Timestamp.A timestamp in RFC3339 UTC "Zulu" format, accurate to nanoseconds. Example: "2014-10-02T15:01:23.045123456Z".

**Comment by hiranya911** [comment] 2020-10-26 18:18
Duplicate of #153

**Closed by hiranya911** 2020-10-26 18:18 UTC
