### ISSUE TITLE
SendAllAsync(IEnumerable<Message> messages, CancellationToken cancellationToken) has error with System.Net.Http.HttpRequestException: The SSL connection could not be established

### ISSUE THREAD

**Issue by bingtianyiyan** [firebase/firebase-admin-dotnet#283] opened 2021-01-25 07:54 UTC
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux
  * Firebase SDK version: 1.170
  * Firebase Product: _____ (auth, database, storage, etc)
  * .NET version: 3.1
  * OS: _____

#### Relevant Code:
coeds: and i use polly to retry once when error ocur

 await FirebaseMessaging.DefaultInstance.SendMulticastAsync(message)

// TODO(you): code here to reproduce the problem
  job execute every one minutes once,we have 150000  batch count ,and one minutes with 9000 batch count,
the ocur happen when we send msg one minutes total count  is 9000 batch count,with 90 batch count once send it ,but somestime it will happen
errors with below:

FirebaseAdmin.Messaging.FirebaseMessagingException: Unknown error while making a remote service call: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Google.Apis.Requests.BatchRequest.ExecuteAsync(CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendBatchRequestAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendMulticastAsync(MulticastMessage message, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendMulticastAsync(MulticastMessage message, Boolean dryRun)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendMulticastAsync(MulticastMessage message)
   at Job.DomainService.FirebaseMgr.FirebaseSendMsgHelper.<>c__DisplayClass0_0.<<SendMsgBatchAsync>b__1>d.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
  System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Google.Apis.Requests.BatchRequest.ExecuteAsync(CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendBatchRequestAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)

**Comment by bingtianyiyan** [comment] 2021-01-25 07:55
I think it is caused by too frequent request interface, but there is no clear official limit, we have purchased an unlimited service

**Comment by bingtianyiyan** [comment] 2021-01-25 08:01
Now I Task.delay(100) 100 milliseconds before sending the call, and unfortunately I still get the same error,so i take to issue,and i see the source code and no find any solutions

**Comment by hiranya911** [comment] 2021-01-25 19:22
```
---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
```

Looks like a network issue or some other low-level SSL handshake problem. Does it happen for all invocations or only some of them? 

I came across the following discussion thread which seems to outline a similar problem: https://stackoverflow.com/questions/30664566/authentication-failed-because-remote-party-has-closed-the-transport-stream

**Comment by bingtianyiyan** [comment] 2021-01-26 01:58
it happen in sometime ,It's okay to visit less frequently,However, when a large amount of data is sent in batches, the above errors may start to be reported within a certain 10 minutes, and then stop when the data is almost ready to be sent.  
Yesterday, there were about 15W pieces of data, 90 pieces for each batch. It was pushed within about 30 minutes after production, and this kind of problem was reported in about 10 minutes.The total number of visits was 1666
 low-level SSL handshake problem?happen in server end or push end ?   
y

**Comment by bingtianyiyan** [comment] 2021-01-26 03:29
today:also have blow questions ,and have new questions with sdk-version=2.0.0.0 ,i update nuget to 2.0.0.0,and batch send=500,and error is low then yesterday , batch num=100 . I think requently use api in small time will happen。

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.GetAccessTokenForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.ServiceCredential.GetAccessTokenWithHeadersForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.ServiceCredential.InterceptAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Google.Apis.Http.ConfigurableMessageHandler.CredentialInterceptAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Google.Apis.Requests.BatchRequest.ExecuteAsync(CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendBatchRequestAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendMulticastAsync(MulticastMessage message, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendMulticastAsync(MulticastMessage message, Boolean dryRun)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendMulticastAsync(MulticastMessage message)
   at Job.DomainService.FirebaseMgr.FirebaseSendMsgHelper.<>c__DisplayClass0_0.<<SendMsgBatchAsync>b__1>d.MoveNext() in /home/jenkins/agent/workspace/Prod-Ludo-Netcore-JobPublish-Build/Job.Services/MsgPushTools/FirebaseMgr/FirebaseSendMsgHelper.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

**Comment by bingtianyiyan** [comment] 2021-01-26 07:47
i download google.api.core github code source:chage this add code below ->
 handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; }; 
but is should see result in product environment tomorrow

  /// <summary>
        /// Creates a simple client handler with redirection and compression disabled.
        /// </summary>
        private HttpClientHandler CreateAndConfigureClientHandler()
        {
            var handler = CreateClientHandler();
            if (handler.SupportsRedirectConfiguration)
            {
                handler.AllowAutoRedirect = false;
            }
            if (handler.SupportsAutomaticDecompression)
            {
                handler.AutomaticDecompression = DecompressionMethods.None;
            }
//Add this
            handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            return handler;
        }

**Comment by hiranya911** [comment] 2021-01-26 19:53
@bingtianyiyan I'm having some difficulty understanding your implementation and the steps you've tried so far. It would be great if you can describe your problem with some code (ideally a complete, minimal example that others can run to reproduce the error). 

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

That looks like something explicitly cancelled the send operation. My guess is Polly cancelled a pending operation, and retried (I'm not familiar with Polly, so I cannot confirm).

**Comment by bingtianyiyan** [comment] 2021-01-27 01:24
i use below code to send and use polly to retry if fail。problem：System.Threading.Tasks.TaskCanceledException: A task was canceled you point is version2.0.0 sdk inner  have refresh token before send msg to check token is expired and get refresh token,but sometimes fail and cancel task。 i  guess like something timeout
sdk:FirebaseAdmin 2.0.0
code below：
 /// <summary>
        ///
        /// </summary>
        /// <returns></returns>
        public static async Task<BatchResponse> SendMsgBatchAsync(MulticastMessage message)
        {
            return await Policy.Handle<Exception>()
                       .WaitAndRetryAsync(1, retryAttempt => TimeSpan.FromSeconds(Math.Pow(20, retryAttempt)))
                       .ExecuteAsync(async () =>
                       {
                           return await FirebaseMessaging.DefaultInstance.SendMulticastAsync(message);
                       }
                       );
        }

**Comment by bingtianyiyan** [comment] 2021-01-27 06:33
today product works better then yesterday,and only hve single one error occur ->  System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

so i will add additional code below like this.and wait tomorrow the result of running batch data。I have no better choice to retry error to occur like product.
  /// <summary>
        /// Creates a simple client handler with redirection and compression disabled.
        /// </summary>
        private HttpClientHandler CreateAndConfigureClientHandler()
        {
            var handler = CreateClientHandler();
            if (handler.SupportsRedirectConfiguration)
            {
                handler.AllowAutoRedirect = false;
            }
            if (handler.SupportsAutomaticDecompression)
            {
                handler.AutomaticDecompression = DecompressionMethods.None;
            }
            // add code
            handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
           
           //today add code 
           handler.SslProtocols = SslProtocols.Ssl3 | SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls;
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            return handler;
        }

**Comment by hiranya911** [comment] 2021-01-27 20:26
I don't fully understand what you're are trying to tell. But I will try my best to explain a few things that might be helpful.

1. Refreshing and fetching tokens is done by the `Google.Apis.Auth` package. As far as I know, the behavior of this package has not changed in a long time.
2. The refresh tokens task runs as part of the same async task as your send operation. It is not a separate background task.
3. `FirebaseAdmin` never cancels any tasks. I doubt `Google.Apis.Auth` does either. So my guess is it's Polly that's cancelling tasks in order to retry them. 
4. It seems you can register a pre-retry callback with Polly. I suggest you implement that and log all the information for debug purposes:

```csharp
Policy
  .Handle<SomeExceptionType>()
  .WaitAndRetry(new[]
  {
    TimeSpan.FromSeconds(1),
    TimeSpan.FromSeconds(2),
    TimeSpan.FromSeconds(3)
  }, (exception, timeSpan, context) => {
    // Add logic to be executed before each retry, such as logging    
  });
```

For the most part this issue looks like an issue caused by the runtime environment (TLS config or other dependencies) or the network. It's unlikely to be a general bug. I'd recommend reaching out to Firebase Support for further help: https://firebase.google.com/support/troubleshooter/report

**Comment by bingtianyiyan** [comment] 2021-01-28 01:17
Thanks for your advice

**Comment by hiranya911** [comment] 2021-02-05 22:17
I'm going to close this since I don't see a reason to believe this is the direct result of a bug in the codebase. Feel free to contact Firebase Support if the problem continues to occur.

**Closed by hiranya911** 2021-02-05 22:17 UTC
Labels: needs-triage
